# Generated by Django 5.2.9 on 2026-01-03 13:32

import vacancies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_min_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateField(null=True, validators=[vacancies.models.check_date_not_past]),
        ),
    ]
