# Generated by Django 5.2.9 on 2026-01-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
